services:
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=${PG_DATABASE}
      - POSTGRES_USER=${PG_USERNAME}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    command: >
      /bin/sh -c "
        chmod +x /docker-entrypoint-initdb.d/init-db.sh &&
        docker-entrypoint.sh postgres"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "sleep 10 && node app.js"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_DATABASE=${PG_DATABASE}
      - PG_USERNAME=${PG_USERNAME}
      - PG_PASSWORD=${PG_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - vnp_TmnCode=${vnp_TmnCode}
      - vnp_HashSecret=${vnp_HashSecret}
      - vnp_Url=${vnp_Url}
      - GA_TRACKING_ID=${GA_TRACKING_ID}
    depends_on:
      - postgres

volumes:
  postgres-data: